#lang info

(define deps '("base"))

;; base color
(define base00 #(0 0 0))
(define base01 #(255 83 112))
(define base02 #(195 232 141))
(define base03 #(255 203 107))
(define base04 #(130 170 255))
(define base05 #(199 146 234))
(define base06 #(137 221 255))
(define base07 #(238 255 255))
(define base08 #(84 110 122))
(define base09 base01)
(define base0A base02)
(define base0B base03)
(define base0C base04)
(define base0D base05)
(define base0E base06)
(define base0F base07)
;; color scheme
(define background #(38 50 56))
(define foreground #(238 255 255))
(define selection #(102 114 120))
(define black base00)
(define black_br base08)
(define red base01)
(define green base02)
(define yellow base03)
(define blue base04)
(define magenta base05)
(define cyan base06)
(define white base07)
(define orange #(247 140 108))

(define framework:color-schemes
  `(#hash((name . "Material Theme - Default")
          (white-on-black-base? . #t)
          (colors
           .
           ((drracket:syncheck:matching-identifiers            ,selection)
            (framework:basic-canvas-background                 ,background)
            (framework:default-text-color                      ,foreground)
            (framework:misspelled-text-color                   ,red)
            (framework:paren-match-color                       ,selection)
            (drracket:check-syntax:both-obligation-style-pref  ,green)
            (drracket:check-syntax:free-variable               ,red)
            (drracket:check-syntax:imported                    ,magenta)
            (drracket:check-syntax:lexically-bound             ,blue)
            (drracket:check-syntax:my-obligation-style-pref    ,orange)
            (drracket:check-syntax:set!d                       ,orange)
            (drracket:check-syntax:their-obligation-style-pref ,cyan)
            (drracket:check-syntax:unk-obligation-style-pref   ,red)
            (drracket:check-syntax:unused-require              ,red)
            (drracket:read-eval-print-loop:error-color         ,red)
            (drracket:read-eval-print-loop:out-color           ,magenta)
            (drracket:read-eval-print-loop:value-color         ,blue)
            (framework:syntax-color:scheme:comment             ,black_br)
            (framework:syntax-color:scheme:constant            ,orange)
            (framework:syntax-color:scheme:error               ,red)
            (framework:syntax-color:scheme:hash-colon-keyword  ,blue)
            (framework:syntax-color:scheme:keyword             ,magenta)
            (framework:syntax-color:scheme:other               ,yellow)
            (framework:syntax-color:scheme:parenthesis         ,cyan)
            (framework:syntax-color:scheme:string              ,green)
            (framework:syntax-color:scheme:symbol              ,foreground)
            (framework:syntax-color:scheme:text                ,green)
            (plt:htdp:test-coverage-off                        ,red)
            (plt:htdp:test-coverage-on                         ,yellow)
            (plt:module-language:test-coverage-off             ,red)
            (plt:module-language:test-coverage-on              ,yellow))))))